### ISSUE TITLE
Issue with sample react native app

### ISSUE THREAD

**Issue by dibyajyotibehera** [KevinAst/feature-u#28]
**This library looks really interesting and I am looking forward to use it . 
-----------------------------------
When using it for a plain react native project I got some errors and am blocked .
Can you please advise where I am going wrong with this hello world project.
--------------**
Steps to reproduce -
1. Clone the project - https://github.com/dibyajyotibehera/FDDDemo.git
2.In the project : npm install && npm run android
3. Emulator shows error 

Error logs - 

ExceptionsManager.js:126 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <Context.Provider />. Did you accidentally export a JSX literal instead of a component?

ExceptionsManager.js:44 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by sylvainlg** [comment]
Hi

Do you use feature-redux ?
We have found the same kind of issue with the last version of redux and
react-redux. We are currently investigating.

Le ven. 28 févr. 2020 13:28, Dibyajyoti Behera <notifications@github.com> a
écrit :

**Comment by dibyajyotibehera** [comment]
No I am not using feaure-redux as of now.

**Comment by KevinAst** [comment]
This error appears to be a rudimentary issue unrelated to feature-u.  In googling this error, I have seen discussions of incorrect import of react components (e.g. default vs. named imports).  With that said, I do not see this issue in a manual review of your code.

When I run into issues like this, it is always helpful to attempt to isolate the problem through a gradual introduction of the various artifacts.

- I would start by injecting some logs in an attempt to determine the component that is causing the problem.
  * in the `ContainerApp` component (logging the render content)
  * in the `main` feature `appWillStart()` callback (registering it's execution)
  * in the `registerRootAppElm()` callback (dumping the rootAppElm)

- Given the simplicity of your initial template, you could try removing feature-u from the mix altogether, to determine if you can reproduce the problem.  In `index.js`, replace the launchApp() invocation with:

  ```js
  import ContainerApp from './features/main/component/ContainerApp';

  // comment out launchApp
  // ... snip snip

  // replace with this:
  // this is in affect the current rendition of your app
  AppRegistry.registerComponent(appName, () => <ContainerApp/>)
  ```

Because I do not currently have react-native tooled up, I am reluctant to spend the time installing the environment (emulator, etal) to run your sample.  Perhaps @sylvainlg may be kind enough to try this in his environment?

**Comment by dibyajyotibehera** [comment]
Thanks Kevin .

- I had spent some time in debugging this issue without luck so far using react native debugger.
- I also got the same sort of google links hence I substantially simplified my project to include only bare minimum of feature-u

- I am able to run the app without feauture-u.
- The problem seems to that at the time of registering the rootAppElem is Context.Provider . I was not able to debug further why feature-u is creating this root elem.This is also the same warning i pasted in the logs in the issue.
- Requested logs as below -
=================================================
in app will start of container app --- [object Object]
index.js:15 rootAppelem being registered is --[object Object]

{$$typeof: Symbol(react.element), type: {…}, key: null, ref: null, props: {…}, …}
$$typeof: Symbol(react.element)
children: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
value: {get: ƒ, hasFeature: ƒ}
**type: {$$typeof: Symbol(**react.provider**), _context: {…}}**

**Comment by KevinAst** [comment]
**feature-u** does inject a `<FassetsContext.Provider>` in the root of your app, supporting the promotion of `fassets`, via either [`withFassets()`](https://feature-u.js.org/cur/api.html#withFassets) HoC or [`useFassets()`](https://feature-u.js.org/cur/api.html#useFassets) custom react hook.  You can see this in the code [here](https://github.com/KevinAst/feature-u/blob/master/src/core/launchApp.js#L564-L598).

The highlighted code shows how the `rootAppElm` is accumulated from all aspects/features.  The context is being added in the section demarked with the **FOURTH** comment.

I can't imagine how this would be causing a problem.  It is very rudimentary to the operation of **feature-u** and has been running for a long time.  The only caveat in your app is you have no Aspects, however in looking through **feature-u** logic, I can't see how that would be causing an issue :-(

You may try enabling the internal **feature-u** logging probes to see if they reveal something ... add this code just before your `launchApp()` invocation:

```js
// diagnostic probes ... just before launchApp()
launchApp.diag.logf.enable();
launchApp.diag.logf.elm2html = (elm) => elm; // attempt to see the accumulative react element content

// now invoke launchApp() as normal
... snip snip
```

**Comment by KevinAst** [comment]
**P.S.** Not wanting to spend the time to install the react-native environment (to run your app), I mimicked your code in a plain web-app, and everything works fine!  Not sure what this means?  I don't think there is a RN issue ... I know that @sylvainlg has been using **feature-u** in RN.

**Question**: Do you receive an initial log entry from **feature-u** ... something like this:

```
***feature-u*** Context in-use: native (React >16.3)... React Version: 16.8.6
```

If so, this tells me that **feature-u** is using the **native** react context utility and NOT pony filling it.

**Comment by sylvainlg** [comment]
I'm in vacation without my computer until thursday.
I will take a closer look a the issue when i go back home


Le ven. 28 févr. 2020 23:52, Kevin Bridges <notifications@github.com> a
écrit :

**Comment by KevinAst** [comment]
Thanks @sylvainlg!

**Comment by dibyajyotibehera** [comment]
I do get the log indicating react native context :

***feature-u*** Context in-use: native (React >16.3)... React Version: 16.9.0

**Comment by sylvainlg** [comment]
Hi

I don't know why the app doesn't start but, in your implementation, you are using feature-u in a strange way.

The actual way to declare an app is more like (quick and dirty) :

```js
// ---------------------------------------
// Feature main : declare a screen
// features/main/main.js
const MainScreen = () => <Text>Hello World</Text>
export default createFeature({
  name: 'mainFeature',
  routes: [
    <Route exact path="/" component={MainScreen} />
    // <Route path="/about" component={About} />
    // <Route path="/topics" component={Topics} />
  ]
});

// ---------------------------------------
// aspects/routes/routes.js: Aspect routes
let accumulatedRoutes = []
export const createRoutesAspect = () => {

  return createAspect({ name='routes',
    validateFeatureContent,
    assembleFeatureContent,
    initialRootAppElm, })
}

const validateFeatureContent = (feature) => {
  if(has(feature, 'routes')) return 'Feature must have routes'
}

const assembleFeatureContent = (fassets, activeFeatures) => {
  accumulatedRoutes = activeFeatures.reduce((accum, feature) => {
    return [...accum, feature['routes']];
  }, [])
}

const initialRootAppElm = () => {

  if (curRootAppElm) {
    throw new Error(
      '***ERROR*** Please register routesAspect before other Aspects ' +
        'that inject content in the rootAppElm ... <AppContainer> does NOT support children.'
    );
  }

  return (
    <NativeRouter>
      {accumulatedRoutes.map((route) => route)}
    </NativeRouter>
  )
}

```
The main feature must declare only specification (name and routes). Is the aspect purpose to create the `NativeRouter` and set the app root element.

Is that more clear about how feature-u work ?

**Comment by dibyajyotibehera** [comment]
In your example createFeature() -takes an object with a field called 'routes'.
Where is the documentation for this . 
I referred this and did not find any field called 'routes'
https://feature-u.js.org/cur/api.html#createFeature

----------
createFeature({
  name: 'mainFeature',
  routes: [
    <Route exact path="/" component={MainScreen} />
    // <Route path="/about" component={About} />
    // <Route path="/topics" component={Topics} />
  ]
});
----------------

**Comment by KevinAst** [comment]
I suspect the app has merely been "trimmed" down to a minimalistic rendition to highlight the issue he is seeing.

Even though it is a very basic template, it should operate (from what I can see).

Presumably the error is coming from **feature-u** attempting to inject the `<FassetsContext.Provider>` in the root of the app.

I could not repeat this in a similar web-app.

I'm more interested in seeing if the error he is seeing can be reproduced in RN by cloning his project.

It's a very simple app template.  If the error can be repeated, then tweak it to see if the error is project related or something in **feature-u**?

**Comment by KevinAst** [comment]
From what I can tell, the following html should be rendered.

The `<FassetsContext.Provider>` is injected by feature-u [here](https://github.com/KevinAst/feature-u/blob/master/src/core/launchApp.js#L564-L598) (see the **FOURTH** comment).

```html
<FassetsContext.Provider value={fassets}> ... injected from feature-u (for fassets promotion)
  <ContainerApp>                          ... injected from app's `main` feature
    <Text>Feature Driven Development - Demo</Text>
  </ContainerApp>
</FassetsContext.Provider>
```
